### PR TITLE
Fixed the pointless DepDownloader being abstract and requiring to implement it

### PR DESCRIPTION
**Pull request by Mitchellbrine**
It was just a waste of resources before. It should work just as intended with the PR I'm going to make in the wrapper.

### CODE REVIEW

**Comment by Kubuxu** [comment]
@RX14 I am leaving this to you as this you have declared to create DepDownloader.

**Comment by Kubuxu** [comment]
@Mitchellbrine the first commit is somehow weird. Could you try fixing it?

**Comment by Mitchellbrine** [comment]
The first commit was me merging all the previous changes into the fork. It makes absolutely no changes because it was me catching up to master.

**Comment by Victorious3** [comment]
@Mitchellbrine Commit your changes, then rebase. That's how you can get rid of the merge commits.

**Pull request merged**
