### PR TITLE
Gradle publishing

### PR DESCRIPTION
**Pull request by magik6k**

### CODE REVIEW

**Comment by RX14** [comment]
everything in build.properties can go in gradle.properties, they do exactly the same thing except gradle.properties is automatically loaded.

**Comment by RX14** [comment]
Also, paths should never be hard coded in, they should be stored in the environment or in a properties file which is not in the git repo, because it is non-potable config which be easy to accidentally commit changes because the file is in git.

**Comment by RX14** [comment]
arxhivesBaseName shouldn't be set because rootProject.name is set

**Comment by magik6k** [comment]
This is early version made just to launch maven repo, it will be improved

**Comment by RX14** [comment]
Also, can you separate the java doc into a separate PR. I can fix all the other issues tomorrow.

**Comment by RX14** [comment]
Also, (and this is to everyone in @NOVAAPI ), can we stop the merge commits, there is a simple git setting which you can look up which automatically does git pull --rebase on a specific branch, and a global setting which sets this up for all new branches.

**Comment by magik6k** [comment]
Sorry, I won't made separate PR, as I don't see the point of it. I made the javadoc fixes so that gradle works. The config file is separated because I don't really like to use main gradle config for this purpose, as it is loaded from few places.
Can you please marge it in so I can continue work on CI and maven repo?

**Comment by magik6k** [comment]
missclick

**Comment by RX14** [comment]
I'll fix it tomorrow...

**Pull request merged**
